### ISSUE TITLE
Could not load experiment/metaworld. Available options: mtrl

### ISSUE THREAD

**Issue by emigmo** [facebookresearch/mtrl#1]
config/config.yaml as :
```
defaults:
  - setup: metaworld
  - experiment: ${defaults.0.setup}
  - agent: sac
  - agent/components: ${defaults.0.setup}_actor
  - agent/components: ${defaults.0.setup}_critic
  - agent/components: ${defaults.0.setup}_encoder
  - agent/components: ${defaults.0.setup}_transition_model
  # - agent/components: task_to_encoder_cluster
  - agent/components: ${defaults.0.setup}_mask
  - agent/components: ${defaults.0.setup}_multitask
  - agent/components: ${defaults.0.setup}_transition_model
  - agent/components: ${defaults.0.setup}_gradnorm
  - agent/components: ${defaults.0.setup}_task_to_encoder_cluster
  - agent/optimizers: ${defaults.0.setup}_actor
  - agent/optimizers: ${defaults.0.setup}_alpha
  - agent/optimizers: ${defaults.0.setup}_critic
  - agent/optimizers: ${defaults.0.setup}_decoder
  - agent/optimizers: ${defaults.0.setup}_encoder
  - env: ???
  - replay_buffer: mtrl
  - logger: mtrl
  - metrics: ${defaults.0.setup}
  - logbook: mtrl
```
The error is shown in the screenshot. I'm new for the hydra and I just want to run a sample demo (metaworld and dm_control env are ok)
![log](https://user-images.githubusercontent.com/10398640/110075703-31575f80-7dbe-11eb-91ec-1e0a6f62a3f0.png)
